_Pragma("once");

#include <Types.hpp>
    
namespace color_c {

// Macro for float color_t
#define COLOR_STRUCT_F(name, hex) static color_t name = { ((float)(((hex) >> 16) & 0xFF))/255.0f, ((float)(((hex) >> 8) & 0xFF))/255.0f, ((float)((hex) & 0xFF))/255.0f };

COLOR_STRUCT_F( alice_blue_c            , 0xf0f8ff)
COLOR_STRUCT_F( antique_white_c         , 0xfaebd7)
COLOR_STRUCT_F( aqua_c                  , 0x00ffff)
COLOR_STRUCT_F( aquamarine_c            , 0x7fffd4)
COLOR_STRUCT_F( azure_c                 , 0xf0ffff)
COLOR_STRUCT_F( beige_c                 , 0xf5f5dc)
COLOR_STRUCT_F( bisque_c                , 0xffe4c4)
COLOR_STRUCT_F( black_c                 , 0x000000)
COLOR_STRUCT_F( blanched_almond_c       , 0xffebcd)
COLOR_STRUCT_F( blue_c                  , 0x0000ff)
COLOR_STRUCT_F( blue_violet_c           , 0x8a2be2)
COLOR_STRUCT_F( brown_c                 , 0xa52a2a)
COLOR_STRUCT_F( burly_wood_c            , 0xdeb887)
COLOR_STRUCT_F( cadet_blue_c            , 0x5f9ea0)
COLOR_STRUCT_F( chartreuse_c            , 0x7fff00)
COLOR_STRUCT_F( chocolate_c             , 0xd2691e)
COLOR_STRUCT_F( coral_c                 , 0xff7f50)
COLOR_STRUCT_F( cornflower_blue_c       , 0x6495ed)
COLOR_STRUCT_F( cornsilk_c              , 0xfff8dc)
COLOR_STRUCT_F( crimson_c               , 0xdc143c)
COLOR_STRUCT_F( cyan_c                  , 0x00ffff)
COLOR_STRUCT_F( dark_blue_c             , 0x00008b)
COLOR_STRUCT_F( dark_cyan_c             , 0x008b8b)
COLOR_STRUCT_F( dark_goldenrod_c        , 0xb8860b)
COLOR_STRUCT_F( dark_gray_c             , 0xa9a9a9)
COLOR_STRUCT_F( dark_green_c            , 0x006400)
COLOR_STRUCT_F( dark_khaki_c            , 0xbdb76b)
COLOR_STRUCT_F( dark_magenta_c          , 0x8b008b)
COLOR_STRUCT_F( dark_olive_green_c      , 0x556B2f)
COLOR_STRUCT_F( dark_orange_c           , 0xff8c00)
COLOR_STRUCT_F( dark_orchid_c           , 0x9932cc)
COLOR_STRUCT_F( dark_red_c              , 0x8b0000)
COLOR_STRUCT_F( dark_salmon_c           , 0xe9967a)
COLOR_STRUCT_F( dark_sea_green_c        , 0x8fbc8f)
COLOR_STRUCT_F( dark_slate_blue_c       , 0x483d8b)
COLOR_STRUCT_F( dark_slate_gray_c       , 0x2f4f4f)
COLOR_STRUCT_F( dark_turquoise_c        , 0x00ced1)
COLOR_STRUCT_F( dark_violet_c           , 0x9400d3)
COLOR_STRUCT_F( deep_pink_c             , 0xff1493)
COLOR_STRUCT_F( deep_sky_blue_c         , 0x00bfff)
COLOR_STRUCT_F( dim_gray_c              , 0x696969)
COLOR_STRUCT_F( dodger_blue_c           , 0x1e90ff)
COLOR_STRUCT_F( firebrick_c             , 0xb22222)
COLOR_STRUCT_F( floral_white_c          , 0xfffaf0)
COLOR_STRUCT_F( forest_green_c          , 0x228b22)
COLOR_STRUCT_F( fuchsia_c               , 0xff00ff)
COLOR_STRUCT_F( gainsboro_c             , 0xdcdcdc)
COLOR_STRUCT_F( ghost_white_c           , 0xf8f8ff)
COLOR_STRUCT_F( gold_c                  , 0xffd700)
COLOR_STRUCT_F( goldenrod_c             , 0xdaa520)
COLOR_STRUCT_F( gray_c                  , 0x808080)
COLOR_STRUCT_F( green_c                 , 0x008000)
COLOR_STRUCT_F( green_yellow_c          , 0xadff2f)
COLOR_STRUCT_F( honeydew_c              , 0xf0fff0)
COLOR_STRUCT_F( hot_pink_c              , 0xff69b4)
COLOR_STRUCT_F( indian_red_c            , 0xcd5c5c)
COLOR_STRUCT_F( indigo_c                , 0x4b0082)
COLOR_STRUCT_F( ivory_c                 , 0xfffff0)
COLOR_STRUCT_F( khaki_c                 , 0xf0e68c)
COLOR_STRUCT_F( lavender_c              , 0xe6e6fa)
COLOR_STRUCT_F( lavender_blush_c        , 0xfff0f5)
COLOR_STRUCT_F( lawn_green_c            , 0x7cfc00)
COLOR_STRUCT_F( lemon_chiffon_c         , 0xfffacd)
COLOR_STRUCT_F( light_blue_c            , 0xadd8e6)
COLOR_STRUCT_F( light_coral_c           , 0xf08080)
COLOR_STRUCT_F( light_cyan_c            , 0xe0ffff)
COLOR_STRUCT_F( light_goldenrod_yellow_c, 0xfafad2)
COLOR_STRUCT_F( light_green_c           , 0x90ee90)
COLOR_STRUCT_F( light_gray_c            , 0xd3d3d3)
COLOR_STRUCT_F( light_pink_c            , 0xffb6c1)
COLOR_STRUCT_F( light_salmon_c          , 0xffa07a)
COLOR_STRUCT_F( light_sea_green_c       , 0x20b2aa)
COLOR_STRUCT_F( light_sky_blue_c        , 0x87cefa)
COLOR_STRUCT_F( light_slate_gray_c      , 0x778899)
COLOR_STRUCT_F( light_steel_blue_c      , 0xb0c4de)
COLOR_STRUCT_F( light_yellow_c          , 0xffffe0)
COLOR_STRUCT_F( lime_c                  , 0x00ff00)
COLOR_STRUCT_F( lime_green_c            , 0x32cd32)
COLOR_STRUCT_F( linen_c                 , 0xfaf0e6)
COLOR_STRUCT_F( magenta_c               , 0xff00ff)
COLOR_STRUCT_F( maroon_c                , 0x800000)
COLOR_STRUCT_F( medium_aquamarine_c     , 0x66cdaa)
COLOR_STRUCT_F( medium_blue_c           , 0x0000cd)
COLOR_STRUCT_F( medium_orchid_c         , 0xba55d3)
COLOR_STRUCT_F( medium_purple_c         , 0x9370db)
COLOR_STRUCT_F( medium_sea_green_c      , 0x3cb371)
COLOR_STRUCT_F( medium_slate_blue_c     , 0x7b68ee)
COLOR_STRUCT_F( medium_spring_green_c   , 0x00fa9a)
COLOR_STRUCT_F( medium_turquoise_c      , 0x48d1cc)
COLOR_STRUCT_F( medium_violet_red_c     , 0xc71585)
COLOR_STRUCT_F( midnight_blue_c         , 0x191970)
COLOR_STRUCT_F( mint_cream_c            , 0xf5fffa)
COLOR_STRUCT_F( misty_rose_c            , 0xffe4e1)
COLOR_STRUCT_F( moccasin_c              , 0xffe4b5)
COLOR_STRUCT_F( navajo_white_c          , 0xffdead)
COLOR_STRUCT_F( navy_c                  , 0x000080)
COLOR_STRUCT_F( old_lace_c              , 0xfdf5e6)
COLOR_STRUCT_F( olive_c                 , 0x808000)
COLOR_STRUCT_F( olive_drab_c            , 0x6b8e23)
COLOR_STRUCT_F( orange_c                , 0xffa500)
COLOR_STRUCT_F( orange_red_c            , 0xff4500)
COLOR_STRUCT_F( orchid_c                , 0xda70d6)
COLOR_STRUCT_F( pale_goldenrod_c        , 0xeee8aa)
COLOR_STRUCT_F( pale_green_c            , 0x98fb98)
COLOR_STRUCT_F( pale_turquoise_c        , 0xafeeee)
COLOR_STRUCT_F( pale_violet_red_c       , 0xdb7093)
COLOR_STRUCT_F( papaya_whip_c           , 0xffefd5)
COLOR_STRUCT_F( peach_puff_c            , 0xffdab9)
COLOR_STRUCT_F( peru_c                  , 0xcd853f)
COLOR_STRUCT_F( pink_c                  , 0xffc0cb)
COLOR_STRUCT_F( plum_c                  , 0xdda0dd)
COLOR_STRUCT_F( powder_blue_c           , 0xb0e0e6)
COLOR_STRUCT_F( purple_c                , 0x800080)
COLOR_STRUCT_F( red_c                   , 0xff0000)
COLOR_STRUCT_F( rosy_brown_c            , 0xbc8f8f)
COLOR_STRUCT_F( royal_blue_c            , 0x4169e1)
COLOR_STRUCT_F( saddle_brown_c          , 0x8b4513)
COLOR_STRUCT_F( salmon_c                , 0xfa8072)
COLOR_STRUCT_F( sandy_brown_c           , 0xf4a460)
COLOR_STRUCT_F( sea_green_c             , 0x2e8B57)
COLOR_STRUCT_F( sea_shell_c             , 0xfff5ee)
COLOR_STRUCT_F( sienna_c                , 0xa0522d)
COLOR_STRUCT_F( silver_c                , 0xc0c0c0)
COLOR_STRUCT_F( sky_blue_c              , 0x87ceeb)
COLOR_STRUCT_F( slate_blue_c            , 0x6a5acd)
COLOR_STRUCT_F( slate_gray_c            , 0x708090)
COLOR_STRUCT_F( snow_c                  , 0xfffafa)
COLOR_STRUCT_F( spring_green_c          , 0x00ff7f)
COLOR_STRUCT_F( steel_blue_c            , 0x4682B4)
COLOR_STRUCT_F( tan_c                   , 0xd2b48c)
COLOR_STRUCT_F( teal_c                  , 0x008080)
COLOR_STRUCT_F( thistle_c               , 0xd8bfd8)
COLOR_STRUCT_F( tomato_c                , 0xff6347)
COLOR_STRUCT_F( turquoise_c             , 0x40e0d0)
COLOR_STRUCT_F( violet_c                , 0xee82ee)
COLOR_STRUCT_F( wheat_c                 , 0xf5deb3)
COLOR_STRUCT_F( white_c                 , 0xffffff)
COLOR_STRUCT_F( white_smoke_c           , 0xf5f5f5)
COLOR_STRUCT_F( yellow_c                , 0xffff00)
COLOR_STRUCT_F( yellow_green_c          , 0x9acd32)
} // namespace color_c


// enum Enum { 
//           AliceBlue              =    0xf0f8ff,  
//           AntiqueWhite          = 0xfaebd7,
//         Aqua                  = 0x00ffff,
//         Aquamarine            = 0x7fffd4,
//         Azure                 = 0xf0ffff,
//         Beige                 = 0xf5f5dc,
//         Bisque                = 0xffe4c4,
//         Black                 = 0x000000,
//         BlanchedAlmond        = 0xffebcd,
//         Blue                  = 0x0000ff,
//         BlueViolet            = 0x8a2be2,
//         Brown                 = 0xa52a2a,
//         BurlyWood             = 0xdeb887,
//         CadetBlue             = 0x5f9ea0,
//         Chartreuse            = 0x7fff00,
//         Chocolate             = 0xd2691e,
//         Coral                 = 0xff7f50,
//         CornflowerBlue        = 0x6495ed,
//         Cornsilk              = 0xfff8dc,
//         Crimson               = 0xdc143c,
//         Cyan                  = 0x00ffff,
//         DarkBlue              = 0x00008b,
//         DarkCyan              = 0x008b8b,
//         DarkGoldenrod         = 0xb8860b,
//         DarkGray              = 0xa9a9a9,
//         DarkGreen             = 0x006400,
//         DarkKhaki             = 0xbdb76b,
//         DarkMagenta           = 0x8b008b,
//         DarkOliveGreen        = 0x556B2f,
//         DarkOrange            = 0xff8c00,
//         DarkOrchid            = 0x9932cc,
//         DarkRed               = 0x8b0000,
//         DarkSalmon            = 0xe9967a,
//         DarkSeaGreen          = 0x8fbc8f,
//         DarkSlateBlue         = 0x483d8b,
//         DarkSlateGray         = 0x2f4f4f,
//         DarkTurquoise         = 0x00ced1,
//         DarkViolet            = 0x9400d3,
//         DeepPink              = 0xff1493,
//         DeepSkyBlue           = 0x00bfff,
//         DimGray               = 0x696969,
//         DodgerBlue            = 0x1e90ff,
//         Firebrick             = 0xb22222,
//         FloralWhite           = 0xfffaf0,
//         ForestGreen           = 0x228b22,
//         Fuchsia               = 0xff00ff,
//         Gainsboro             = 0xdcdcdc,
//         GhostWhite            = 0xf8f8ff,
//         Gold                  = 0xffd700,
//         Goldenrod             = 0xdaa520,
//         Gray                  = 0x808080,
//         Green                 = 0x008000,
//         GreenYellow           = 0xadff2f,
//         Honeydew              = 0xf0fff0,
//         HotPink               = 0xff69b4,
//         IndianRed             = 0xcd5c5c,
//         Indigo                = 0x4b0082,
//         Ivory                 = 0xfffff0,
//         Khaki                 = 0xf0e68c,
//         Lavender              = 0xe6e6fa,
//         LavenderBlush         = 0xfff0f5,
//         LawnGreen             = 0x7cfc00,
//         LemonChiffon          = 0xfffacd,
//         LightBlue             = 0xadd8e6,
//         LightCoral            = 0xf08080,
//         LightCyan             = 0xe0ffff,
//         LightGoldenrodYellow  = 0xfafad2,
//         LightGreen            = 0x90ee90,
//         LightGray             = 0xd3d3d3,
//         LightPink             = 0xffb6c1,
//         LightSalmon           = 0xffa07a,
//         LightSeaGreen         = 0x20b2aa,
//         LightSkyBlue          = 0x87cefa,
//         LightSlateGray        = 0x778899,
//         LightSteelBlue        = 0xb0c4de,
//         LightYellow           = 0xffffe0,
//         Lime                  = 0x00ff00,
//         LimeGreen             = 0x32cd32,
//         Linen                 = 0xfaf0e6,
//         Magenta               = 0xff00ff,
//         Maroon                = 0x800000,
//         MediumAquamarine      = 0x66cdaa,
//         MediumBlue            = 0x0000cd,
//         MediumOrchid          = 0xba55d3,
//         MediumPurple          = 0x9370db,
//         MediumSeaGreen        = 0x3cb371,
//         MediumSlateBlue       = 0x7b68ee,
//         MediumSpringGreen     = 0x00fa9a,
//         MediumTurquoise       = 0x48d1cc,
//         MediumVioletRed       = 0xc71585,
//         MidnightBlue          = 0x191970,
//         MintCream             = 0xf5fffa,
//         MistyRose             = 0xffe4e1,
//         Moccasin              = 0xffe4b5,
//         NavajoWhite           = 0xffdead,
//         Navy                  = 0x000080,
//         OldLace               = 0xfdf5e6,
//         Olive                 = 0x808000,
//         OliveDrab             = 0x6b8e23,
//         Orange                = 0xffa500,
//         OrangeRed             = 0xff4500,
//         Orchid                = 0xda70d6,
//         PaleGoldenrod         = 0xeee8aa,
//         PaleGreen             = 0x98fb98,
//         PaleTurquoise         = 0xafeeee,
//         PaleVioletRed         = 0xdb7093,
//         PapayaWhip            = 0xffefd5,
//         PeachPuff             = 0xffdab9,
//         Peru                  = 0xcd853f,
//         Pink                  = 0xffc0cb,
//         Plum                  = 0xdda0dd,
//         PowderBlue            = 0xb0e0e6,
//         Purple                = 0x800080,
//         Red                   = 0xff0000,
//         RosyBrown             = 0xbc8f8f,
//         RoyalBlue             = 0x4169e1,
//         SaddleBrown           = 0x8b4513,
//         Salmon                = 0xfa8072,
//         SandyBrown            = 0xf4a460,
//         SeaGreen              = 0x2e8B57,
//         SeaShell              = 0xfff5ee,
//         Sienna                = 0xa0522d,
//         Silver                = 0xc0c0c0,
//         SkyBlue               = 0x87ceeb,
//         SlateBlue             = 0x6a5acd,
//         SlateGray             = 0x708090,
//         Snow                  = 0xfffafa,
//         SpringGreen           = 0x00ff7f,
//         SteelBlue             = 0x4682B4,
//         Tan                   = 0xd2b48c,
//         Teal                  = 0x008080,
//         Thistle               = 0xd8bfd8,
//         Tomato                = 0xff6347,
//         Turquoise             = 0x40e0d0,
//         Violet                = 0xee82ee,
//         Wheat                 = 0xf5deb3,
//         White                 = 0xffffff,
//         WhiteSmoke            = 0xf5f5f5,
//         Yellow                = 0xffff00,
//         YellowGreen           = 0x9acd32
//     };
